spring:
  application:
    name: chatService


server:
  port: 8081

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

