apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-user-service
  labels:
    app: fb-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-user-service
  template:
    metadata:
      name: fb-user-service
      labels:
        app: fb-user-service
    spec:
      containers:
        - name: fb-user-service
          image: fb-user-service-latest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fb-user-config-map
