apiVersion: v2
name: family-budget
description: A Helm chart for FamilyBudget - full-stack microservices application
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"
maintainers:
  - name: vasyl
