apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "family-budget.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.secrets.postgres.username | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  neo4j-username: "neo4j"
  neo4j-password: {{ .Values.secrets.neo4j.password | quote }}
  neo4j-auth: {{ printf "neo4j/%s" .Values.secrets.neo4j.password | quote }}
